### ISSUE TITLE
Colour Issues

### ISSUE THREAD

**Issue by pburke90** [jamerst/userstyles#2]
This is a great userstyle, but some text boxes are not correct so they are the same colour as the background and can't be seen. I have attached a screenshot with the sections circled in red.

![bbc](https://user-images.githubusercontent.com/56159172/66206339-b9a47300-e6a7-11e9-81d3-1c8ec7c7ed16.PNG)

**Comment by pburke90** [comment]
Many thanks for the fix, I've discovered a few other sections on the page (bbc.co.uk/news/northern_ireland - but may appear on other pages) where the text is still black or grey as below:

![bbc2](https://user-images.githubusercontent.com/56159172/66305368-18136080-e8f7-11e9-8cc3-884a16db6529.PNG)
![bbc3](https://user-images.githubusercontent.com/56159172/66305374-1b0e5100-e8f7-11e9-9289-8e961666db4f.PNG)

**Comment by jamerst** [comment]
Thanks, I'll look into those later.

**Comment by pburke90** [comment]
No worries. I have also discovered the comments section that appears on some articles hasn't changed either, just letting you know. Appreciate this theme, I much prefer dark mode as I find most sites really bright and a strain on the eyes.
