### ISSUE TITLE
Colour issues

### ISSUE THREAD

**Issue by SideSwipe9th** [jamerst/userstyles#4]
It looks like BBC are rolling out an incremental upgrade to their stylesheet some time in the last couple of hours. Article body text is now dark grey, as are hyperlinks in top stories and features. And the sectional toast bar near the top has reverted from black/grey to white on articles only. Screenshot below. 

![image](https://user-images.githubusercontent.com/47156505/118019269-b4fa7300-b350-11eb-99a0-851448e0e324.png)

**Comment by jamerst** [comment]
Thanks for the reminder, I've been meaning to fix this for a while!

These styling issues should be mostly fixed, there's still a few issues with link hovers that need working out.

This userstyle is a bit of a mess, it has a lot of now redundant styles from the old BBC news site. I'll probably rewrite it soon to get rid of those and make it better.
